/// 国家数据模型
class CountryInfo {
  final String code;
  final String name;
  final String flag;

  const CountryInfo({
    required this.code,
    required this.name,
    required this.flag,
  });
}

/// 将国家代码转换为国旗emoji
String getFlagEmoji(String countryCode) {
  final codePoints = countryCode.toUpperCase().codeUnits.map((char) => 127397 + char).toList();
  return String.fromCharCodes(codePoints);
}

/// 完整的国家列表（按名称排序）
const List<CountryInfo> countryList = [
  CountryInfo(code: 'AF', name: 'Afghanistan', flag: '🇦🇫'),
  CountryInfo(code: 'AL', name: 'Albania', flag: '🇦🇱'),
  CountryInfo(code: 'DZ', name: 'Algeria', flag: '🇩🇿'),
  CountryInfo(code: 'AS', name: 'American Samoa', flag: '🇦🇸'),
  CountryInfo(code: 'AD', name: 'Andorra', flag: '🇦🇩'),
  CountryInfo(code: 'AO', name: 'Angola', flag: '🇦🇴'),
  CountryInfo(code: 'AI', name: 'Anguilla', flag: '🇦🇮'),
  CountryInfo(code: 'AQ', name: 'Antarctica', flag: '🇦🇶'),
  CountryInfo(code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬'),
  CountryInfo(code: 'AR', name: 'Argentina', flag: '🇦🇷'),
  CountryInfo(code: 'AM', name: 'Armenia', flag: '🇦🇲'),
  CountryInfo(code: 'AW', name: 'Aruba', flag: '🇦🇼'),
  CountryInfo(code: 'AU', name: 'Australia', flag: '🇦🇺'),
  CountryInfo(code: 'AT', name: 'Austria', flag: '🇦🇹'),
  CountryInfo(code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿'),
  CountryInfo(code: 'BS', name: 'Bahamas', flag: '🇧🇸'),
  CountryInfo(code: 'BH', name: 'Bahrain', flag: '🇧🇭'),
  CountryInfo(code: 'BD', name: 'Bangladesh', flag: '🇧🇩'),
  CountryInfo(code: 'BB', name: 'Barbados', flag: '🇧🇧'),
  CountryInfo(code: 'BY', name: 'Belarus', flag: '🇧🇾'),
  CountryInfo(code: 'BE', name: 'Belgium', flag: '🇧🇪'),
  CountryInfo(code: 'BZ', name: 'Belize', flag: '🇧🇿'),
  CountryInfo(code: 'BJ', name: 'Benin', flag: '🇧🇯'),
  CountryInfo(code: 'BM', name: 'Bermuda', flag: '🇧🇲'),
  CountryInfo(code: 'BT', name: 'Bhutan', flag: '🇧🇹'),
  CountryInfo(code: 'BO', name: 'Bolivia', flag: '🇧🇴'),
  CountryInfo(code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦'),
  CountryInfo(code: 'BW', name: 'Botswana', flag: '🇧🇼'),
  CountryInfo(code: 'BR', name: 'Brazil', flag: '🇧🇷'),
  CountryInfo(code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴'),
  CountryInfo(code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬'),
  CountryInfo(code: 'BN', name: 'Brunei', flag: '🇧🇳'),
  CountryInfo(code: 'BG', name: 'Bulgaria', flag: '🇧🇬'),
  CountryInfo(code: 'BF', name: 'Burkina Faso', flag: '🇧🇫'),
  CountryInfo(code: 'BI', name: 'Burundi', flag: '🇧🇮'),
  CountryInfo(code: 'KH', name: 'Cambodia', flag: '🇰🇭'),
  CountryInfo(code: 'CM', name: 'Cameroon', flag: '🇨🇲'),
  CountryInfo(code: 'CA', name: 'Canada', flag: '🇨🇦'),
  CountryInfo(code: 'CV', name: 'Cape Verde', flag: '🇨🇻'),
  CountryInfo(code: 'KY', name: 'Cayman Islands', flag: '🇰🇾'),
  CountryInfo(code: 'CF', name: 'Central African Republic', flag: '🇨🇫'),
  CountryInfo(code: 'TD', name: 'Chad', flag: '🇹🇩'),
  CountryInfo(code: 'CL', name: 'Chile', flag: '🇨🇱'),
  CountryInfo(code: 'CN', name: 'China', flag: '🇨🇳'),
  CountryInfo(code: 'CX', name: 'Christmas Island', flag: '🇨🇽'),
  CountryInfo(code: 'CC', name: 'Cocos Islands', flag: '🇨🇨'),
  CountryInfo(code: 'CO', name: 'Colombia', flag: '🇨🇴'),
  CountryInfo(code: 'KM', name: 'Comoros', flag: '🇰🇲'),
  CountryInfo(code: 'CK', name: 'Cook Islands', flag: '🇨🇰'),
  CountryInfo(code: 'CR', name: 'Costa Rica', flag: '🇨🇷'),
  CountryInfo(code: 'HR', name: 'Croatia', flag: '🇭🇷'),
  CountryInfo(code: 'CU', name: 'Cuba', flag: '🇨🇺'),
  CountryInfo(code: 'CW', name: 'Curaçao', flag: '🇨🇼'),
  CountryInfo(code: 'CY', name: 'Cyprus', flag: '🇨🇾'),
  CountryInfo(code: 'CZ', name: 'Czech Republic', flag: '🇨🇿'),
  CountryInfo(code: 'CD', name: 'Democratic Republic of the Congo', flag: '🇨🇩'),
  CountryInfo(code: 'DK', name: 'Denmark', flag: '🇩🇰'),
  CountryInfo(code: 'DJ', name: 'Djibouti', flag: '🇩🇯'),
  CountryInfo(code: 'DM', name: 'Dominica', flag: '🇩🇲'),
  CountryInfo(code: 'DO', name: 'Dominican Republic', flag: '🇩🇴'),
  CountryInfo(code: 'TL', name: 'East Timor', flag: '🇹🇱'),
  CountryInfo(code: 'EC', name: 'Ecuador', flag: '🇪🇨'),
  CountryInfo(code: 'EG', name: 'Egypt', flag: '🇪🇬'),
  CountryInfo(code: 'SV', name: 'El Salvador', flag: '🇸🇻'),
  CountryInfo(code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶'),
  CountryInfo(code: 'ER', name: 'Eritrea', flag: '🇪🇷'),
  CountryInfo(code: 'EE', name: 'Estonia', flag: '🇪🇪'),
  CountryInfo(code: 'ET', name: 'Ethiopia', flag: '🇪🇹'),
  CountryInfo(code: 'FK', name: 'Falkland Islands', flag: '🇫🇰'),
  CountryInfo(code: 'FO', name: 'Faroe Islands', flag: '🇫🇴'),
  CountryInfo(code: 'FJ', name: 'Fiji', flag: '🇫🇯'),
  CountryInfo(code: 'FI', name: 'Finland', flag: '🇫🇮'),
  CountryInfo(code: 'FR', name: 'France', flag: '🇫🇷'),
  CountryInfo(code: 'GF', name: 'French Guiana', flag: '🇬🇫'),
  CountryInfo(code: 'PF', name: 'French Polynesia', flag: '🇵🇫'),
  CountryInfo(code: 'GA', name: 'Gabon', flag: '🇬🇦'),
  CountryInfo(code: 'GM', name: 'Gambia', flag: '🇬🇲'),
  CountryInfo(code: 'GE', name: 'Georgia', flag: '🇬🇪'),
  CountryInfo(code: 'DE', name: 'Germany', flag: '🇩🇪'),
  CountryInfo(code: 'GH', name: 'Ghana', flag: '🇬🇭'),
  CountryInfo(code: 'GI', name: 'Gibraltar', flag: '🇬🇮'),
  CountryInfo(code: 'GR', name: 'Greece', flag: '🇬🇷'),
  CountryInfo(code: 'GL', name: 'Greenland', flag: '🇬🇱'),
  CountryInfo(code: 'GD', name: 'Grenada', flag: '🇬🇩'),
  CountryInfo(code: 'GP', name: 'Guadeloupe', flag: '🇬🇵'),
  CountryInfo(code: 'GU', name: 'Guam', flag: '🇬🇺'),
  CountryInfo(code: 'GT', name: 'Guatemala', flag: '🇬🇹'),
  CountryInfo(code: 'GG', name: 'Guernsey', flag: '🇬🇬'),
  CountryInfo(code: 'GN', name: 'Guinea', flag: '🇬🇳'),
  CountryInfo(code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼'),
  CountryInfo(code: 'GY', name: 'Guyana', flag: '🇬🇾'),
  CountryInfo(code: 'HT', name: 'Haiti', flag: '🇭🇹'),
  CountryInfo(code: 'HN', name: 'Honduras', flag: '🇭🇳'),
  CountryInfo(code: 'HK', name: 'Hong Kong', flag: '🇭🇰'),
  CountryInfo(code: 'HU', name: 'Hungary', flag: '🇭🇺'),
  CountryInfo(code: 'IS', name: 'Iceland', flag: '🇮🇸'),
  CountryInfo(code: 'IN', name: 'India', flag: '🇮🇳'),
  CountryInfo(code: 'ID', name: 'Indonesia', flag: '🇮🇩'),
  CountryInfo(code: 'IR', name: 'Iran', flag: '🇮🇷'),
  CountryInfo(code: 'IQ', name: 'Iraq', flag: '🇮🇶'),
  CountryInfo(code: 'IE', name: 'Ireland', flag: '🇮🇪'),
  CountryInfo(code: 'IM', name: 'Isle of Man', flag: '🇮🇲'),
  CountryInfo(code: 'IL', name: 'Israel', flag: '🇮🇱'),
  CountryInfo(code: 'IT', name: 'Italy', flag: '🇮🇹'),
  CountryInfo(code: 'CI', name: 'Ivory Coast', flag: '🇨🇮'),
  CountryInfo(code: 'JM', name: 'Jamaica', flag: '🇯🇲'),
  CountryInfo(code: 'JP', name: 'Japan', flag: '🇯🇵'),
  CountryInfo(code: 'JE', name: 'Jersey', flag: '🇯🇪'),
  CountryInfo(code: 'JO', name: 'Jordan', flag: '🇯🇴'),
  CountryInfo(code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿'),
  CountryInfo(code: 'KE', name: 'Kenya', flag: '🇰🇪'),
  CountryInfo(code: 'KI', name: 'Kiribati', flag: '🇰🇮'),
  CountryInfo(code: 'XK', name: 'Kosovo', flag: '🇽🇰'),
  CountryInfo(code: 'KW', name: 'Kuwait', flag: '🇰🇼'),
  CountryInfo(code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬'),
  CountryInfo(code: 'LA', name: 'Laos', flag: '🇱🇦'),
  CountryInfo(code: 'LV', name: 'Latvia', flag: '🇱🇻'),
  CountryInfo(code: 'LB', name: 'Lebanon', flag: '🇱🇧'),
  CountryInfo(code: 'LS', name: 'Lesotho', flag: '🇱🇸'),
  CountryInfo(code: 'LR', name: 'Liberia', flag: '🇱🇷'),
  CountryInfo(code: 'LY', name: 'Libya', flag: '🇱🇾'),
  CountryInfo(code: 'LI', name: 'Liechtenstein', flag: '🇱🇮'),
  CountryInfo(code: 'LT', name: 'Lithuania', flag: '🇱🇹'),
  CountryInfo(code: 'LU', name: 'Luxembourg', flag: '🇱🇺'),
  CountryInfo(code: 'MO', name: 'Macau', flag: '🇲🇴'),
  CountryInfo(code: 'MK', name: 'Macedonia', flag: '🇲🇰'),
  CountryInfo(code: 'MG', name: 'Madagascar', flag: '🇲🇬'),
  CountryInfo(code: 'MW', name: 'Malawi', flag: '🇲🇼'),
  CountryInfo(code: 'MY', name: 'Malaysia', flag: '🇲🇾'),
  CountryInfo(code: 'MV', name: 'Maldives', flag: '🇲🇻'),
  CountryInfo(code: 'ML', name: 'Mali', flag: '🇲🇱'),
  CountryInfo(code: 'MT', name: 'Malta', flag: '🇲🇹'),
  CountryInfo(code: 'MH', name: 'Marshall Islands', flag: '🇲🇭'),
  CountryInfo(code: 'MQ', name: 'Martinique', flag: '🇲🇶'),
  CountryInfo(code: 'MR', name: 'Mauritania', flag: '🇲🇷'),
  CountryInfo(code: 'MU', name: 'Mauritius', flag: '🇲🇺'),
  CountryInfo(code: 'YT', name: 'Mayotte', flag: '🇾🇹'),
  CountryInfo(code: 'MX', name: 'Mexico', flag: '🇲🇽'),
  CountryInfo(code: 'FM', name: 'Micronesia', flag: '🇫🇲'),
  CountryInfo(code: 'MD', name: 'Moldova', flag: '🇲🇩'),
  CountryInfo(code: 'MC', name: 'Monaco', flag: '🇲🇨'),
  CountryInfo(code: 'MN', name: 'Mongolia', flag: '🇲🇳'),
  CountryInfo(code: 'ME', name: 'Montenegro', flag: '🇲🇪'),
  CountryInfo(code: 'MS', name: 'Montserrat', flag: '🇲🇸'),
  CountryInfo(code: 'MA', name: 'Morocco', flag: '🇲🇦'),
  CountryInfo(code: 'MZ', name: 'Mozambique', flag: '🇲🇿'),
  CountryInfo(code: 'MM', name: 'Myanmar', flag: '🇲🇲'),
  CountryInfo(code: 'NA', name: 'Namibia', flag: '🇳🇦'),
  CountryInfo(code: 'NR', name: 'Nauru', flag: '🇳🇷'),
  CountryInfo(code: 'NP', name: 'Nepal', flag: '🇳🇵'),
  CountryInfo(code: 'NL', name: 'Netherlands', flag: '🇳🇱'),
  CountryInfo(code: 'NC', name: 'New Caledonia', flag: '🇳🇨'),
  CountryInfo(code: 'NZ', name: 'New Zealand', flag: '🇳🇿'),
  CountryInfo(code: 'NI', name: 'Nicaragua', flag: '🇳🇮'),
  CountryInfo(code: 'NE', name: 'Niger', flag: '🇳🇪'),
  CountryInfo(code: 'NG', name: 'Nigeria', flag: '🇳🇬'),
  CountryInfo(code: 'NU', name: 'Niue', flag: '🇳🇺'),
  CountryInfo(code: 'NF', name: 'Norfolk Island', flag: '🇳🇫'),
  CountryInfo(code: 'KP', name: 'North Korea', flag: '🇰🇵'),
  CountryInfo(code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵'),
  CountryInfo(code: 'NO', name: 'Norway', flag: '🇳🇴'),
  CountryInfo(code: 'OM', name: 'Oman', flag: '🇴🇲'),
  CountryInfo(code: 'PK', name: 'Pakistan', flag: '🇵🇰'),
  CountryInfo(code: 'PW', name: 'Palau', flag: '🇵🇼'),
  CountryInfo(code: 'PS', name: 'Palestine', flag: '🇵🇸'),
  CountryInfo(code: 'PA', name: 'Panama', flag: '🇵🇦'),
  CountryInfo(code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬'),
  CountryInfo(code: 'PY', name: 'Paraguay', flag: '🇵🇾'),
  CountryInfo(code: 'PE', name: 'Peru', flag: '🇵🇪'),
  CountryInfo(code: 'PH', name: 'Philippines', flag: '🇵🇭'),
  CountryInfo(code: 'PN', name: 'Pitcairn', flag: '🇵🇳'),
  CountryInfo(code: 'PL', name: 'Poland', flag: '🇵🇱'),
  CountryInfo(code: 'PT', name: 'Portugal', flag: '🇵🇹'),
  CountryInfo(code: 'PR', name: 'Puerto Rico', flag: '🇵🇷'),
  CountryInfo(code: 'QA', name: 'Qatar', flag: '🇶🇦'),
  CountryInfo(code: 'CG', name: 'Republic of the Congo', flag: '🇨🇬'),
  CountryInfo(code: 'RE', name: 'Reunion', flag: '🇷🇪'),
  CountryInfo(code: 'RO', name: 'Romania', flag: '🇷🇴'),
  CountryInfo(code: 'RU', name: 'Russia', flag: '🇷🇺'),
  CountryInfo(code: 'RW', name: 'Rwanda', flag: '🇷🇼'),
  CountryInfo(code: 'BL', name: 'Saint Barthelemy', flag: '🇧🇱'),
  CountryInfo(code: 'SH', name: 'Saint Helena', flag: '🇸🇭'),
  CountryInfo(code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳'),
  CountryInfo(code: 'LC', name: 'Saint Lucia', flag: '🇱🇨'),
  CountryInfo(code: 'MF', name: 'Saint Martin', flag: '🇲🇫'),
  CountryInfo(code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲'),
  CountryInfo(code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨'),
  CountryInfo(code: 'WS', name: 'Samoa', flag: '🇼🇸'),
  CountryInfo(code: 'SM', name: 'San Marino', flag: '🇸🇲'),
  CountryInfo(code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹'),
  CountryInfo(code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦'),
  CountryInfo(code: 'SN', name: 'Senegal', flag: '🇸🇳'),
  CountryInfo(code: 'RS', name: 'Serbia', flag: '🇷🇸'),
  CountryInfo(code: 'SC', name: 'Seychelles', flag: '🇸🇨'),
  CountryInfo(code: 'SL', name: 'Sierra Leone', flag: '🇸🇱'),
  CountryInfo(code: 'SG', name: 'Singapore', flag: '🇸🇬'),
  CountryInfo(code: 'SX', name: 'Sint Maarten', flag: '🇸🇽'),
  CountryInfo(code: 'SK', name: 'Slovakia', flag: '🇸🇰'),
  CountryInfo(code: 'SI', name: 'Slovenia', flag: '🇸🇮'),
  CountryInfo(code: 'SB', name: 'Solomon Islands', flag: '🇸🇧'),
  CountryInfo(code: 'SO', name: 'Somalia', flag: '🇸🇴'),
  CountryInfo(code: 'ZA', name: 'South Africa', flag: '🇿🇦'),
  CountryInfo(code: 'KR', name: 'South Korea', flag: '🇰🇷'),
  CountryInfo(code: 'SS', name: 'South Sudan', flag: '🇸🇸'),
  CountryInfo(code: 'ES', name: 'Spain', flag: '🇪🇸'),
  CountryInfo(code: 'LK', name: 'Sri Lanka', flag: '🇱🇰'),
  CountryInfo(code: 'SD', name: 'Sudan', flag: '🇸🇩'),
  CountryInfo(code: 'SR', name: 'Suriname', flag: '🇸🇷'),
  CountryInfo(code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯'),
  CountryInfo(code: 'SZ', name: 'Swaziland', flag: '🇸🇿'),
  CountryInfo(code: 'SE', name: 'Sweden', flag: '🇸🇪'),
  CountryInfo(code: 'CH', name: 'Switzerland', flag: '🇨🇭'),
  CountryInfo(code: 'SY', name: 'Syria', flag: '🇸🇾'),
  CountryInfo(code: 'TW', name: 'Taiwan', flag: '🇹🇼'),
  CountryInfo(code: 'TJ', name: 'Tajikistan', flag: '🇹🇯'),
  CountryInfo(code: 'TZ', name: 'Tanzania', flag: '🇹🇿'),
  CountryInfo(code: 'TH', name: 'Thailand', flag: '🇹🇭'),
  CountryInfo(code: 'TG', name: 'Togo', flag: '🇹🇬'),
  CountryInfo(code: 'TK', name: 'Tokelau', flag: '🇹🇰'),
  CountryInfo(code: 'TO', name: 'Tonga', flag: '🇹🇴'),
  CountryInfo(code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹'),
  CountryInfo(code: 'TN', name: 'Tunisia', flag: '🇹🇳'),
  CountryInfo(code: 'TR', name: 'Turkey', flag: '🇹🇷'),
  CountryInfo(code: 'TM', name: 'Turkmenistan', flag: '🇹🇲'),
  CountryInfo(code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨'),
  CountryInfo(code: 'TV', name: 'Tuvalu', flag: '🇹🇻'),
  CountryInfo(code: 'VI', name: 'U.S. Virgin Islands', flag: '🇻🇮'),
  CountryInfo(code: 'UG', name: 'Uganda', flag: '🇺🇬'),
  CountryInfo(code: 'UA', name: 'Ukraine', flag: '🇺🇦'),
  CountryInfo(code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪'),
  CountryInfo(code: 'GB', name: 'United Kingdom', flag: '🇬🇧'),
  CountryInfo(code: 'US', name: 'United States', flag: '🇺🇸'),
  CountryInfo(code: 'UY', name: 'Uruguay', flag: '🇺🇾'),
  CountryInfo(code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿'),
  CountryInfo(code: 'VU', name: 'Vanuatu', flag: '🇻🇺'),
  CountryInfo(code: 'VA', name: 'Vatican', flag: '🇻🇦'),
  CountryInfo(code: 'VE', name: 'Venezuela', flag: '🇻🇪'),
  CountryInfo(code: 'VN', name: 'Vietnam', flag: '🇻🇳'),
  CountryInfo(code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫'),
  CountryInfo(code: 'EH', name: 'Western Sahara', flag: '🇪🇭'),
  CountryInfo(code: 'YE', name: 'Yemen', flag: '🇾🇪'),
  CountryInfo(code: 'ZM', name: 'Zambia', flag: '🇿🇲'),
  CountryInfo(code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼'),
];
